---
title: "Plotly"
output: 
  html_document: 
    toc: true
    toc_float: true
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

### loading and tidying the instacart dataset

```{r instacart_data}
# loading dataset
data("instacart")

# tidying dataset 
instacart_df =
  instacart %>% 
  janitor::clean_names() %>% 
  filter(
    department %in% c("frozen"), 
    order_dow == 6
  )
```

### making a barplot 

```{r bar_plot}
instacart_df %>% 
  count(aisle) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis") %>% 
  layout(title = "Items ordered in each aisle on day 6", 
         xaxis = list(title = "Frozen food aisle"),
         yaxis = list(title = "Number of items ordered"))
```

### making a boxplot 

```{r box_plot}
instacart_df %>% 
  mutate(aisle = fct_reorder(aisle, order_hour_of_day)) %>% 
  plot_ly(y = ~order_hour_of_day, color = ~aisle, type = "box", colors = "viridis") %>% 
  layout(title = "Order hour of the day per aisle on day 6", 
         xaxis = list(title = "Frozen food aisle"),
         yaxis = list(title = "Order hour of the day"))
```

### making a histogram 

```{r histogram}
instacart_df %>% 
  plot_ly(x = ~days_since_prior_order, color = ~aisle, type = "histogram", colors = "viridis") %>% 
  layout(title = "Count of days since prior order for each frozen food aisle on day 6",
         x = "Days since prior order",
         y = "Count")
```

<br>

Click here to return to the [main](index.html) page. 