---
title: "Resume"
---

<br> 

**Education**

* Columbia University Mailman School of Public Health | M.S. Biostatistics | 08/2021 - Present
* University of Rochester | B.S. Biological Sciences: Microbiology | 08/2016 - 05/2020

<br> 

**Work Experience**

* Columbia University Department of Biostatistics | Data Entry Specialist | 10/2021 - Present 
  * Responsible for reviewing and abstracting data from standardized neurological/neurophysiological exams into case report forms. 
  
* Tempus | Jr. Clinical Data Abstractor | 05/2020 - 07/2021
  * Responsible for extracting, structuring, and analyzing multiple clinical data sources to build a database of oncology data
  * Maintained high abstraction quality by consistently achieving quality assurance (QA) scores greater than 90%
  
<br> 

**Research Experience** 

* University of Rochester Department of Psychology | Project BRIDGE Research Intern | 10/2019 - 06/2020
  * Project: Multi-method longitudinal study on family functioning and adolescent development 
  * Independent minute-by-minute observational coding of parent and adolescent interactions
  
* University of Rochester Medical Center | Independent Research Project | 09/2018 - 08/2019 
  * Project: Effectiveness of canine and equine live-attenuated influenza vaccines based on the temperature- sensitive, cold-adapted and attenuated mutations of a Russian Master Donor Virus
  * Laboratory work applying cell tissue culture, gel electrophoresis, plasmid isolation and purification, MaxiPrep, bacterial transformation, minigenome assay, virus transfection and rescue, hemagglutinin assay, plaque assay, and data analysis using GraphPad Prism
  * Attendance and participation in group meetings by giving oral research presentations

* Boston Children’s Hospital | Summer Research Intern | 05/2018 - 08/2018 
  * Laboratory work applying MaxiPrep, growing and maintaining bacterial cultures, NanoDrop, and data
analysis
  * Attendance and participation in group meetings
  
* Boston Children’s Hospital | Summer Research Intern | 05/2017 - 08/2017 
  * Assisted in a project studying the function of hematopoietic stem cells and RHO GTPase (Rac and RhoH)
  * Laboratory work applying cell tissue culture, virus transfection, DNA extraction from bone marrow, NanoDrop, MaxiPrep, and data analysis
  * Attendance and participation in group meetings by giving an oral research presentation
  
* Dana-Farber Cancer Institute | Summer Research Intern | 06/2016 - 08/2016 
  * Assisted in projects studying early precursor conditions leading to Multiple Myeloma and circulating exosomes present in patients diagnosed with Waldenstrom Macroglobulinemia
  * Laboratory work applying cell tissue culture, transformation of competent cells with plasmid DNA, MaxiPrep, NanoDrop, and data analysis
  * Attendance and participation in group meetings
  
<br> 

**Teaching Experience**

* University of Rochester Department of Statistics | Teaching Assistant | 08/2019 - 05/2020
  * Led two weekly recitations involving teaching statistical concepts and R software
  * Proctored exams and maintained attendance records for students
  * Assisted students with homework assignments and group projects
  
* University of Rochester Center for Community Leadership | Tutor | 08/2017 - 05/2020
  * Tutored elementary aged children by promoting active learning through play
  * Worked individually with a specific partner child to monitor academic goals
  * Collaborated with a team to develop lesson plans for weekly tutoring sessions
  
<br>
  
**Presentations** 

1. Juliette Marie Charlotte Bouyssou, BSc, MSc, Yosra Aljawai, MSc, Amir Yosef, MD, Salomon Manier, MD, Ragyie Rawal, Katsutoshi Kokubun, PhD, Adriana Perilla Glen, MBA, Antonio Sacco, BS, RN, Jorge J. Castillo, MD, Steven P Treon, MD, PhD, Aldo M. Roccaro, MD, PhD, Marzia Capelletti, PhD, MMSc, Olivier Hermine, MD, PhD and Irene M. Ghobrial, MD. “Profiling of Circulating Exosomes in Patients with Waldenstrom Macroglobulinemia”. Poster presented at American Society of Hematology, 58th Annual Meeting, Dec. 3-6, 2016, San Diego, CA.

<br>

**Skills** 

* Software: Python, R/R Studio, GraphPad Prism
* Basic: MS Office (Excel, Word, PowerPoint), ChemDraw, Macintosh, Windows OS
* Language: English, Nepali

<br> 

Click here to return to the [main](index.html) page. 